# Disease Prediction based on Symtoms

In [35]:
#Importing Libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle
# Libraries to clean data
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
# Libraries to perform feature selection
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
# Libraries to train models
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
# Libraries to evaluate performance
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score, precision_score

# Cleaning the Data

In [2]:
# Reading the Training.csv file
df_train = pd.read_csv("data/Training.csv")

In [3]:
# Dropping unnecessary columns
df_train = df_train.drop('Unnamed: 133', axis=1)
df_train.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection


In [4]:
# List of columns names (i.e.symptoms)
df_train.columns.tolist()

['itching',
 'skin_rash',
 'nodal_skin_eruptions',
 'continuous_sneezing',
 'shivering',
 'chills',
 'joint_pain',
 'stomach_pain',
 'acidity',
 'ulcers_on_tongue',
 'muscle_wasting',
 'vomiting',
 'burning_micturition',
 'spotting_ urination',
 'fatigue',
 'weight_gain',
 'anxiety',
 'cold_hands_and_feets',
 'mood_swings',
 'weight_loss',
 'restlessness',
 'lethargy',
 'patches_in_throat',
 'irregular_sugar_level',
 'cough',
 'high_fever',
 'sunken_eyes',
 'breathlessness',
 'sweating',
 'dehydration',
 'indigestion',
 'headache',
 'yellowish_skin',
 'dark_urine',
 'nausea',
 'loss_of_appetite',
 'pain_behind_the_eyes',
 'back_pain',
 'constipation',
 'abdominal_pain',
 'diarrhoea',
 'mild_fever',
 'yellow_urine',
 'yellowing_of_eyes',
 'acute_liver_failure',
 'fluid_overload',
 'swelling_of_stomach',
 'swelled_lymph_nodes',
 'malaise',
 'blurred_and_distorted_vision',
 'phlegm',
 'throat_irritation',
 'redness_of_eyes',
 'sinus_pressure',
 'runny_nose',
 'congestion',
 'chest_pain',


In [5]:
# Check null columns 
null_cols = [col for col in df_train.columns if df_train[col].isnull().sum() > 0]
null_cols

[]

In [6]:
df_train.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection


In [7]:
df_train.columns = df_train.columns.str.replace('_', ' ')

In [8]:
# List of prognosis
df_train['prognosis'].value_counts().sort_index()

(vertigo) Paroymsal  Positional Vertigo    120
AIDS                                       120
Acne                                       120
Alcoholic hepatitis                        120
Allergy                                    120
Arthritis                                  120
Bronchial Asthma                           120
Cervical spondylosis                       120
Chicken pox                                120
Chronic cholestasis                        120
Common Cold                                120
Dengue                                     120
Diabetes                                   120
Dimorphic hemmorhoids(piles)               120
Drug Reaction                              120
Fungal infection                           120
GERD                                       120
Gastroenteritis                            120
Heart attack                               120
Hepatitis B                                120
Hepatitis C                                120
Hepatitis D  

In [9]:
# Splitting data into features and target
X = df_train.drop('prognosis', axis=1)
y = df_train[["prognosis"]]
y = np.ravel(y)

In [10]:
y

array(['Fungal infection', 'Fungal infection', 'Fungal infection', ...,
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [11]:
# label encode the target variable
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

[15 15 15 ... 38 35 27]


In [12]:
# Reading the  testing.csv file
df_test = pd.read_csv("data/Testing.csv")

df_test.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction


In [13]:
# Check null columns 
null_cols = [col for col in df_test.columns if df_test[col].isnull().sum() > 0]
null_cols

[]

In [14]:
df_test.columns = df_test.columns.str.replace('_', ' ')

In [15]:
# List of prognosis
df_test['prognosis'].value_counts().sort_index()

(vertigo) Paroymsal  Positional Vertigo    1
AIDS                                       1
Acne                                       1
Alcoholic hepatitis                        1
Allergy                                    1
Arthritis                                  1
Bronchial Asthma                           1
Cervical spondylosis                       1
Chicken pox                                1
Chronic cholestasis                        1
Common Cold                                1
Dengue                                     1
Diabetes                                   1
Dimorphic hemmorhoids(piles)               1
Drug Reaction                              1
Fungal infection                           2
GERD                                       1
Gastroenteritis                            1
Heart attack                               1
Hepatitis B                                1
Hepatitis C                                1
Hepatitis D                                1
Hepatitis 

In [16]:
# Splitting data into features and target
X_test_csv= df_test.drop('prognosis', axis=1)
y_test_csv = df_test[["prognosis"]]
y_test_csv = np.ravel(y_test_csv)

In [17]:
# label encode the target variable
y_test_csv = le.transform(y_test_csv)
print(y_test_csv)

[15  4 16  9 14 33  1 12 17  6 23 30  7 32 28 29  8 11 37 40 19 20 21 22
  3 36 10 34 13 18 39 26 24 25 31  5  0  2 38 35 27 15]


In [18]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, train_size = 0.70, random_state=42)

In [19]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

# Performing Feature Selection

**To select the top 95 features, we used RFE with Random Forest as an estimator**

In [20]:
rfc = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, n_jobs=-1)
n_features = 95
rfe = RFE(estimator=rfc, n_features_to_select=n_features)
X_train_rfe = rfe.fit_transform(X_train, y_train)
X_test_rfe = rfe.transform(X_test)
X_test_csv_rfe = rfe.transform(X_test_csv)

In [21]:
# Get the names of the selected features
selected_feature_names = df_train.columns[:-1][rfe.support_]
selected_feature_names = list(selected_feature_names)
print("Selected features:", selected_feature_names)

Selected features: ['itching', 'nodal skin eruptions', 'shivering', 'chills', 'joint pain', 'stomach pain', 'ulcers on tongue', 'spotting  urination', 'weight gain', 'cold hands and feets', 'weight loss', 'restlessness', 'patches in throat', 'irregular sugar level', 'indigestion', 'headache', 'nausea', 'loss of appetite', 'pain behind the eyes', 'back pain', 'constipation', 'abdominal pain', 'diarrhoea', 'mild fever', 'yellowing of eyes', 'swelling of stomach', 'swelled lymph nodes', 'malaise', 'phlegm', 'throat irritation', 'redness of eyes', 'sinus pressure', 'runny nose', 'congestion', 'chest pain', 'weakness in limbs', 'fast heart rate', 'neck pain', 'dizziness', 'bruising', 'obesity', 'swollen legs', 'enlarged thyroid', 'brittle nails', 'swollen extremeties', 'excessive hunger', 'slurred speech', 'knee pain', 'hip joint pain', 'muscle weakness', 'stiff neck', 'swelling joints', 'movement stiffness', 'spinning movements', 'loss of balance', 'unsteadiness', 'weakness of one body sid

# Train the Models using Selected Features

**To build the precision of the model, we utilized three distinctive algorithms which are as per the following**
* Decision Tree algorithm
* Random Forest algorithm
* KNearestNeighbour algorithm
* Naive Bayes algorithm
* Support Vector Machines algorithm
* Gradient Boosting algorithm

## Decision Tree Algorithm

In [22]:
dtc = tree.DecisionTreeClassifier(max_depth=37) 
dtc = dtc.fit(X_train_rfe,y_train)

y_pred=dtc.predict(X_test_rfe)
print("Decision Tree")
print("Accuracy of Training.csv Split Data")
print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Number of correct predictions:", accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Decision Tree
Accuracy of Training.csv Split Data
Accuracy score: 0.9512195121951219
Number of correct predictions: 1404
Confusion matrix
[[30  0  0 ...  0  0  0]
 [ 0 32  7 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  2 ... 34  0  0]
 [ 0  0  4 ...  0 33  0]
 [ 0  0  0 ...  0  0 39]]


In [23]:
y_pred=dtc.predict(X_test_csv_rfe)
print("Decision Tree")
print("Accuracy of Testing.csv")
print("Accuracy score:", accuracy_score(y_test_csv, y_pred))
print("Number of correct predictions:", accuracy_score(y_test_csv, y_pred, normalize=False))
print("Precision score:", precision_score(y_test_csv, y_pred, average='weighted', zero_division=1))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test_csv,y_pred)
print(conf_matrix)

Decision Tree
Accuracy of Testing.csv
Accuracy score: 0.9761904761904762
Number of correct predictions: 41
Precision score: 0.9880952380952381
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [24]:
df_results = pd.DataFrame(le.inverse_transform(y_test_csv), le.inverse_transform(y_pred)).reset_index()
df_results = df_results.rename(columns={'index':'Actual', 0:'Predicted'})
df_results

,Actual,Predicted
0,Fungal infection,Fungal infection
1,Allergy,Allergy
2,GERD,GERD
3,Chronic cholestasis,Chronic cholestasis
4,Drug Reaction,Drug Reaction
5,Peptic ulcer diseae,Peptic ulcer diseae
6,AIDS,AIDS
7,Diabetes,Diabetes
8,Gastroenteritis,Gastroenteritis
9,Bronchial Asthma,Bronchial Asthma


## Random Forest Algorithm

In [25]:
rfc = RandomForestClassifier()
rfc = rfc.fit(X_train_rfe,y_train)

# calculating accuracy 
y_pred=rfc.predict(X_test_rfe)
print("Random Forest")
print("Accuracy of Training.csv Split Data")
print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Number of correct predictions:", accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Random Forest
Accuracy of Training.csv Split Data
Accuracy score: 0.986449864498645
Number of correct predictions: 1456
Confusion matrix
[[32  0  0 ...  0  0  0]
 [ 0 32  7 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [26]:
y_pred=rfc.predict(X_test_csv_rfe)
print("Random Forest")
print("Accuracy of Testing.csv")
print("Accuracy score:", accuracy_score(y_test_csv, y_pred))
print("Number of correct predictions:", accuracy_score(y_test_csv, y_pred, normalize=False))
print("Precision score:", precision_score(y_test_csv, y_pred, average='weighted', zero_division=1))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test_csv,y_pred)
print(conf_matrix)

Random Forest
Accuracy of Testing.csv
Accuracy score: 0.9761904761904762
Number of correct predictions: 41
Precision score: 0.9880952380952381
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [27]:
df_results = pd.DataFrame(le.inverse_transform(y_test_csv), le.inverse_transform(y_pred)).reset_index()
df_results = df_results.rename(columns={'index':'Actual', 0:'Predicted'})
df_results

,Actual,Predicted
0,Fungal infection,Fungal infection
1,Allergy,Allergy
2,GERD,GERD
3,Chronic cholestasis,Chronic cholestasis
4,Drug Reaction,Drug Reaction
5,Peptic ulcer diseae,Peptic ulcer diseae
6,AIDS,AIDS
7,Diabetes,Diabetes
8,Gastroenteritis,Gastroenteritis
9,Bronchial Asthma,Bronchial Asthma


## Gradient Boosting

In [28]:
gbc = GradientBoostingClassifier()
gbc=gbc.fit(X_train_rfe,y_train)

y_pred=gbc.predict(X_test_rfe)
print("Gradient Boosting")
print("Accuracy of Training.csv Split Data")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Gradient Boosting
Accuracy of Training.csv Split Data
0.986449864498645
1456
Confusion matrix
[[32  0  0 ...  0  0  0]
 [ 0 32  7 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [29]:
y_pred=gbc.predict(X_test_csv_rfe)
print("Gradient Boosting")
print("Accuracy of Testing.csv")
print("Accuracy score:", accuracy_score(y_test_csv, y_pred))
print("Number of correct predictions:", accuracy_score(y_test_csv, y_pred, normalize=False))
print("Precision score:", precision_score(y_test_csv, y_pred, average='weighted', zero_division=1))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test_csv,y_pred)
print(conf_matrix)

Gradient Boosting
Accuracy of Testing.csv
Accuracy score: 0.9761904761904762
Number of correct predictions: 41
Precision score: 0.9880952380952381
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [30]:
df_results = pd.DataFrame(le.inverse_transform(y_test_csv), le.inverse_transform(y_pred)).reset_index()
df_results = df_results.rename(columns={'index':'Actual', 0:'Predicted'})
df_results

,Actual,Predicted
0,Fungal infection,Fungal infection
1,Allergy,Allergy
2,GERD,GERD
3,Chronic cholestasis,Chronic cholestasis
4,Drug Reaction,Drug Reaction
5,Peptic ulcer diseae,Peptic ulcer diseae
6,AIDS,AIDS
7,Diabetes,Diabetes
8,Gastroenteritis,Gastroenteritis
9,Bronchial Asthma,Bronchial Asthma


## Support Vector Machine

In [31]:
svc = SVC(gamma=100.0, C=1.0)
svc=svc.fit(X_train_rfe,y_train)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
y_pred=svc.predict(X_test_rfe)
print("Support Vector Machine")
print("Accuracy of Training.csv Split Data")
print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Number of correct predictions:", accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Support Vector Machine
Accuracy of Training.csv Split Data
Accuracy score: 0.986449864498645
Number of correct predictions: 1456
Confusion matrix
[[32  0  0 ...  0  0  0]
 [ 0 32  7 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [32]:
y_pred=svc.predict(X_test_csv_rfe)
print("Support Vector Machine")
print("Accuracy of Testing.csv")
print("Accuracy score:", accuracy_score(y_test_csv, y_pred))
print("Number of correct predictions:", accuracy_score(y_test_csv, y_pred, normalize=False))
print("Precision score:", precision_score(y_test_csv, y_pred, average='weighted', zero_division=1))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test_csv,y_pred)
print(conf_matrix)

Support Vector Machine
Accuracy of Testing.csv
Accuracy score: 0.9761904761904762
Number of correct predictions: 41
Precision score: 0.9880952380952381
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [33]:
df_results = pd.DataFrame(le.inverse_transform(y_test_csv), le.inverse_transform(y_pred)).reset_index()
df_results = df_results.rename(columns={'index':'Actual', 0:'Predicted'})
df_results

,Actual,Predicted
0,Fungal infection,Fungal infection
1,Allergy,Allergy
2,GERD,GERD
3,Chronic cholestasis,Chronic cholestasis
4,Drug Reaction,Drug Reaction
5,Peptic ulcer diseae,Peptic ulcer diseae
6,AIDS,AIDS
7,Diabetes,Diabetes
8,Gastroenteritis,Gastroenteritis
9,Bronchial Asthma,Bronchial Asthma


# Pickle the trained models for use in DiagnoBot

In [36]:
with open('le.pkl', 'wb') as f:
    pickle.dump(le, f)

with open('model.pkl', 'wb') as f:
    pickle.dump(svc, f)

with open('rfe_model.pickle', 'wb') as f:
    pickle.dump(rfe, f)