In [1]:
import pickle
import pandas as pd
import numpy as np

In [2]:
# load pickled data
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

with open("rfe_model.pickle", "rb") as f:
    rfe = pickle.load(f)

with open("le.pkl", "rb") as f:
    le = pickle.load(f)

In [3]:
#Reading the training.csv and testing.csv files
df=pd.read_csv("data/Training.csv")
DF= pd.read_csv('data/Testing.csv')

In [4]:
df = df.drop('Unnamed: 133', axis=1)
df.columns = df.columns.str.replace('_', ' ')
df.head()

,itching,skin rash,nodal skin eruptions,continuous sneezing,shivering,chills,joint pain,stomach pain,acidity,ulcers on tongue,...,blackheads,scurring,skin peeling,silver like dusting,small dents in nails,inflammatory nails,blister,red sore around nose,yellow crust ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection


In [5]:
DF.columns = DF.columns.str.replace('_', ' ')
DF.head()

,itching,skin rash,nodal skin eruptions,continuous sneezing,shivering,chills,joint pain,stomach pain,acidity,ulcers on tongue,...,blackheads,scurring,skin peeling,silver like dusting,small dents in nails,inflammatory nails,blister,red sore around nose,yellow crust ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction


In [6]:
feature_names = df.iloc[:,:-1].columns.tolist()
selected_features_indices = rfe.support_
selected_features = [feature_names[i] for i in range(len(feature_names)) if selected_features_indices[i]]
# Print the selected feature names
print("Selected Features:", selected_features)

Selected Features: ['itching', 'nodal skin eruptions', 'shivering', 'chills', 'joint pain', 'stomach pain', 'ulcers on tongue', 'spotting  urination', 'weight gain', 'cold hands and feets', 'weight loss', 'restlessness', 'patches in throat', 'irregular sugar level', 'sweating', 'indigestion', 'headache', 'dark urine', 'nausea', 'loss of appetite', 'pain behind the eyes', 'back pain', 'constipation', 'abdominal pain', 'diarrhoea', 'mild fever', 'yellowing of eyes', 'swelling of stomach', 'swelled lymph nodes', 'malaise', 'phlegm', 'throat irritation', 'redness of eyes', 'sinus pressure', 'runny nose', 'congestion', 'chest pain', 'weakness in limbs', 'fast heart rate', 'neck pain', 'dizziness', 'cramps', 'bruising', 'swollen legs', 'enlarged thyroid', 'brittle nails', 'swollen extremeties', 'slurred speech', 'knee pain', 'hip joint pain', 'muscle weakness', 'stiff neck', 'swelling joints', 'movement stiffness', 'spinning movements', 'loss of balance', 'unsteadiness', 'weakness of one bod

In [7]:
X_test = DF.iloc[:,:-1]
X_test = rfe.transform(X_test)

print(X_test)

[[1 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [1 0 0 ... 0 1 0]]


In [8]:
# Code to test samples

sampleNum = 11

print("Sample {} has the following symptoms:".format(sampleNum))
for i in range(len(selected_features)):
    if X_test[sampleNum][i] == 1:
        print(selected_features[i])
        
print()       
y_pred = model.predict([X_test[sampleNum]])
y_pred = le.inverse_transform(y_pred)
print("The disease prediction for Sample {} is {}".format(sampleNum, y_pred[0])) 

Sample 11 has the following symptoms:
indigestion
headache
stiff neck
depression
irritability
visual disturbances

The disease prediction for Sample 11 is Migraine
